plugins {
    id 'java'
    id 'application'

    id 'war'
    id "org.teavm" version "0.12.3"
}

group = 'org.ballerinalang'
version = '2201.13.0-m3'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':ballerina-lang')
    implementation project(':ballerina-tools-api')

    implementation teavm.libs.jsoApis
}

application {
    mainClass = 'io.ballerina.teavm.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'io.ballerina.teavm.Main'
    }
}

teavm {
    all {
        mainClass = application.mainClass
    }

    js {
        addedToWebApp = true
        targetFileName = 'ballerina.js'
    }

    wasmGC {
        addedToWebApp = true
        targetFileName = 'ballerina.wasm'
    }
}
